############# English navigation ##############

# main menu
[[main]]
name = "Home"
pageRef = "/"
weight = 1

[[main]]
name = "Documentation"
pageRef = "/documents"
weight = 2

[[main]]
name = "F.A.Q."
pageRef = "/faq"
weight = 3



# footer menu
[[footer]]
name = "Home"
pageRef = "/"
weight = 1

[[footer]]
name = "Documentation"
pageRef = "/documents"
weight = 2

[[footer]]
name = "F.A.Q."
pageRef = "/faq"
weight = 3
